<style type="text/css">
body {
	padding: 150px;
	color: #333;
}
a, a:hover {
	text-decoration: none;
	color: #2CC990;
}
.regards {
	text-align: center;
}
article {
	display: block;
	margin: 0 auto;
}
</style>
<article>
	<h1>We're sorry, our site doing maintenance break. We'll back soon :)</h1>
	<h3>If you need help you can always <a href="mailto:<?php echo $carovl['config']['site_email']; ?>">contact us</a>, otherwise we&rsquo;ll be back shortly!</h3>
	<h3 class="regards">&mdash; <?php echo $carovl['config']['site_name']; ?></h3>
</article>