<div class="col-md-10 offset-md-1">
	<div class="row">
		<div class="col-md-8">
			<div class="card notifications">
				<div class="card-header">
					<div class="media">
						<a href="<?php echo $carovl['user']['url']; ?>" data-redirect="?page=timeline&u=<?php echo $carovl['user']['username']; ?>" id="updateusername-<?php echo $carovl['user']['user_id']; ?>">
							<img src="<?php echo $carovl['user']['avatar']; ?>" alt="<?php echo $carovl['user']['username']; ?>" class="d-flex mr-3">
						</a>
						<div class="media-body">
							<h3 class="mt-2">
								<?php echo $carovl['lang']['all_notifications']; ?>
								<span class="float-right">
									<i class="fa fa-bell-o"></i>
								</span>
							</h3>
						</div>
					</div>
				</div>
				<div class="card-block">
					<?php 
					$notifications = getNotifications();
					foreach ($notifications as $carovl['notification']) {
						echo loadPage('notifications/notification-list');
					}
					?>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<?php echo loadPage('sidebar/content'); ?>
		</div>
	</div>
</div>