<div class="col-md-10 offset-md-1">
	<div class="row">
		<div class="col-md-8">
			<div class="card groups">
				<div class="card-header">
					<h4 class="card-title"><?php echo $carovl['lang']['create_group']; ?></h4>
				</div>
				<div class="card-block">
					<div class="alerts"></div>
					<form class="create-group-form" method="post">
						<div class="form-group carovl">
							<input type="text" name="group_name" class="form-control">
							<span class="highlight"></span>
							<span class="bar"></span>
							<label><?php echo $carovl['lang']['group_name_label']; ?></label>
						</div>
						<div class="form-group carovl">
							<input type="text" name="group_title" class="form-control">
							<span class="highlight"></span>
							<span class="bar"></span>
							<label><?php echo $carovl['lang']['group_title_label']; ?></label>
						</div>
						<div class="form-group carovl">
							<textarea name="about" id="about-group" class="form-control" dir="auto"></textarea>
							<span class="highlight"></span>
							<span class="bar"></span>
							<label><?php echo $carovl['lang']['about_label']; ?></label>
						</div>
						<input type="hidden" name="hash_id" value="<?php echo createSession(); ?>">
						<div class="form-group">
							<button type="submit" class="btn btn-carovl" id="create-group">
								<i class="fa fa-plus icon-loader" data-icon="plus"></i> <?php echo $carovl['lang']['create_label']; ?>
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(function () {
	autosize($('#about-group'));
	$('form.create-group-form').ajaxForm({
		url: ajaxRequests() + '?f=groups&s=create_group',
		beforeSend: function () {
			progressLoader($('#create-group'));
			$('#create-group').attr('disabled', true);
		},
		success: function (data) {
			scrollToTop();
			if (data.status == 200) {
				$('.alerts').html('<center><div class="alert alert-success">' + data.success + '</div></center>');
				setTimeout(function() {
					window.location.href = data.href;
				}, 1000);
			} else {
				$('#create-group').attr('disabled', false);
				var errors = data.errors.join("<br>");
				$('.alerts').html('<center><div class="alert alert-danger">' + errors + '</div></center>');
				$('.alert-danger').fadeIn('fast', function () {
					$(this).delay(2500).fadeOut(500, function () {
						$(this).remove();
					});
				});
			}
			progressLoader($('#create-group'));
		}
	});
});
</script>