<div class="card admin">
	<div class="card-header">
		<h3 class="card-title"><?php echo $carovl['lang']['mailing_list']; ?></h3>
	</div>
	<div class="card-block">
		<form class="admin-mailing-list-form" method="post">
			<h4><?php echo $carovl['lang']['compose_new_message']; ?> <small>(<?php echo $carovl['lang']['html_allowed']; ?>)</small></h4>
			<br>
			<div class="form-group carovl">
				<input type="text" class="form-control" name="subject">
				<span class="highlight"></span>
				<span class="bar"></span>
				<label><?php echo $carovl['lang']['subject_label']; ?>:</label>
			</div>
			<div class="form-group carovl">
				<textarea name="message" class="form-control" dir="auto" rows="10"></textarea>
				<span class="highlight"></span>
				<span class="bar"></span>
				<label><?php echo $carovl['lang']['message_label']; ?>:</label>
			</div>
			<div class="form-group carovl">
				<select class="form-control used" name="recipient">
					<option value="all"><?php echo $carovl['lang']['all_users']; ?></option>
					<option value="active"><?php echo $carovl['lang']['active_users']; ?></option>
					<option value="inactive"><?php echo $carovl['lang']['inactive_users']; ?></option>
				</select>
				<span class="highlight"></span>
				<span class="bar"></span>
				<label><?php echo $carovl['lang']['to_label']; ?>:</label>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-carovl">
					<i class="fa fa-paper-plane-o icon-loader" data-icon="paper-plane-o"></i> <?php echo $carovl['lang']['send_label']; ?>
				</button>
			</div>
			<div class="send-info"></div>
		</form>
	</div>
</div>
<script type="text/javascript">
$(function () {
	autosize($('textarea'));
	$('form.admin-mailing-list-form').ajaxForm({
		url: ajaxRequests() + '?f=admin_setting&s=send_mail',
		beforeSend: function () {
			progressLoader($('form.admin-mailing-list-form').find('button'));
			$('form.admin-mailing-list-form').find('button').attr('disabled', true);
			$('.send-info').show().html('<h5><i class="fa fa-clock-o"></i> <span><?php echo $carovl['lang']['please_wait']; ?> <span>.</span> <span>.</span> <span>.</span></span></h5>')
		},
		success: function (data) {
			$('form.admin-mailing-list-form').find('button').attr('disabled', false);
			if (data.status == 200) {
				$('.send-info').hide();
				swal({
					title: "<?php echo $carovl['lang']['message_sent']; ?>",
					type: "success",
					confirmButtonColor: "#2CC990",
				});
			} else if (data.status == 300) {
				$('.send-info').fadeOut('fast');
				swal({
					title: data.error,
					type: "error",
					confirmButtonColor: "#2CC990",
				});
			}
			progressLoader($('form.admin-mailing-list-form').find('button'));
		}
	});
});
</script>