<div class="card setting">
	<?php echo loadPage('setting/header'); ?>
	<div class="card-block">
		<div class="alerts"></div>
		<form class="change-password-form" method="post">
			<?php if ($carovl['setting']['user_id'] == $carovl['user']['user_id']) { ?> 
			<div class="form-group carovl">
				<input type="password" class="form-control new_password" name="current_password">
				<span class="highlight"></span>
				<span class="bar"></span>
				<label><?php echo $carovl['lang']['current_password_label']; ?></label>
			</div>
			<?php } ?>
			<div class="form-group carovl">
				<input type="password" name="new_password" class="form-control">
				<span class="highlight"></span>
				<span class="bar"></span>
				<label><?php echo $carovl['lang']['new_password_label']; ?></label>
			</div>
			<div class="form-group carovl">
				<input type="password" name="confirm_password" class="form-control">
				<span class="highlight"></span>
				<span class="bar"></span>
				<label><?php echo $carovl['lang']['confirm_password_label']; ?></label>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-carovl">
					<i class="fa fa-floppy-o icon-loader" data-icon="floppy-o"></i> <?php echo $carovl['lang']['save_label']; ?>
				</button>
			</div>
			<input type="hidden" name="user_id" value="<?php echo $carovl['setting']['user_id']; ?>">
			<input type="hidden" name="hash_id" value="<?php echo createSession(); ?>">
		</form>
	</div>
</div>
<script type="text/javascript">
$(function () {
	$('form.change-password-form').ajaxForm({
		url: ajaxRequests() + '?f=settings&s=update_user_password',
		beforeSend: function () {
			progressLoader($('form.change-password-form').find('.btn-carovl'));
			$('form.change-password-form').find('.btn-carovl').attr('disabled', true);
		},
		success: function (data) {
			$('form.change-password-form').find('.btn-carovl').attr('disabled', false);
			if (data.status == 200) {
				$('.alerts').html('<center><div class="alert alert-success">' + data.success + '</div></center>');
				$('.alert-success').fadeIn('fast', function () {
					$(this).delay(2500).fadeOut(500, function () {
						$(this).remove();
					});
				});
				$('input').blur();
				$('form.change-password-form').clearForm();
			} else if (data.errors) {
				var errors = data.errors.join('<br>');
				$('.alerts').html('<center><div class="alert alert-danger">' + errors + '</div></center>');
				$('.alert-danger').fadeIn('fast', function () {
					$(this).delay(2500).fadeOut(500, function () {
						$(this).remove();
					});
				});
			}
			progressLoader($('form.change-password-form').find('.btn-carovl'));
		}
	});
});
</script>