<div id="posts" data-story-event="<?php echo $carovl['event']['id']; ?>">
	<?php 
	$stories = getPosts(array(
		'filter_by' => 'all',
		'event_id' => $carovl['event']['id'],
		'limit' => 10
	));
	if (count($stories) == 0) {
		echo loadPage('story/no-event-stories');
	} else {
		foreach ($stories as $carovl['story']) {
			echo loadPage('story/content');
		}
	}
	?>
</div>
<?php if (count($stories) > 0 && $carovl['logged_in'] == true) { ?> 
<div class="card load-more">
	<div class="card-block">
		<div class="get-more-posts pointer" id="get-more-posts" onclick="getMorePosts();">
			<span>
				<i class="fa fa-repeat icon-loader" data-icon="repeat"></i>
			</span>
		</div>
	</div>
</div>
<?php } ?>