<div class="row">
	<div class="col-lg-6 col-xs-6">
		<div class="widget-box bg-blue">
			<div class="inner">
				<h3><?php echo countAllData('comments'); ?></h3>
				<p><?php echo ucfirst($carovl['lang']['comments']); ?></p>
			</div>
			<div class="icon">
				<i class="fa fa-comments"></i>
			</div>
		</div>
	</div>
	<div class="col-lg-6 col-xs-6">
		<div class="widget-box bg-red">
			<div class="inner">
				<h3><?php echo countPostData('likes'); ?></h3>
				<p><?php echo $carovl['lang']['likes']; ?></p>
			</div>
			<div class="icon">
				<i class="fa fa-heart"></i>
			</div>
		</div>
	</div>
</div>
<div class="card admin">
	<div class="card-block">
		<div class="table-responsive">
			<table class="table table-hover table-condensed">
				<thead>
					<tr>
						<th><?php echo $carovl['lang']['id']; ?></th>
						<th><?php echo $carovl['lang']['publisher']; ?></th>
						<th><?php echo $carovl['lang']['post']; ?></th>
						<th><?php echo $carovl['lang']['time']; ?></th>
						<th><?php echo $carovl['lang']['action']; ?></th>
					</tr>
				</thead>
				<tbody class="result post-list">
					<?php 
					$posts = getAllPosts();
					if (count($posts) > 0) {
						foreach ($posts as $carovl['story']) {
							echo loadPage('admin/posts/post-list');
						}
					}
					?>
				</tbody>
			</table>
		</div>
		<input type="hidden" name="hash_id" id="hash_id" value="<?php echo createSession(); ?>">
		<?php if (count($posts) == 0) { ?> 
		<div class="view-more-wrapper view-more-articles">
			<span class="text-center btn btn-white">
				<?php echo $carovl['lang']['no_data']; ?>
			</span>
		</div>
		<?php } elseif (count($posts) >= 10) { ?> 
		<div class="view-more-wrapper view-more-posts">
			<span class="text-center btn btn-white" onclick="getMorePostsAdmin();">
				<i class="fa fa-arrow-down icon-loader" data-icon="arrow-down"></i> <?php echo $carovl['lang']['show_more_posts']; ?>
			</span>
		</div>
		<?php } ?>
	</div>
</div>
<script type="text/javascript">
function deletePostAdmin(post_id) {
	hash_id = $('#hash_id').val();
	swal({
		title: "<?php echo $carovl['lang']['delete_post_confirmation']; ?>",
		type: "warning",
		showCancelButton: true,
		confirmButtonColor: "#2CC990",
		confirmButtonText: "<?php echo $carovl['lang']['delete_label']; ?>",
		cancelButtonText: "<?php echo $carovl['lang']['nevermind_label']; ?>",
		showLoaderOnConfirm: true,
		closeOnConfirm: false,
	}, function () {
		$.post(ajaxRequests() + '?f=admin_setting&s=delete_post', {
			post_id: post_id,
			hash_id: hash_id
		}, function (data) {
			if (data.status == 200) {
				$('#post_id_' + post_id).fadeOut(300, function () {
					$(this).remove();
				});
				swal.close();
			}
		});
	});
}
<?php if (count($posts) >= 10) { ?> 
function getMorePostsAdmin() {
	view_more_wrapper = $('.view-more-posts');
	after_post_id = $('.post-list').find('.list:last').attr('data-post-id');
	progressLoader(view_more_wrapper.find('.btn-white'));
	$.get(ajaxRequests() + '?f=admin_setting&s=get_more_posts', {
		after_post_id: after_post_id
	}, function (data) {
		if (data.html.length != 0) {
			$('tbody.result').append(data.html);
		} else {
			view_more_wrapper.html('<span class="text-center btn btn-white" onclick="getMorePostsAdmin();"><?php echo $carovl['lang']['no_more_posts']; ?></span>').fadeOut('slow');
		}
		progressLoader(view_more_wrapper.find('.btn-white'));
	});
}
<?php } ?>
</script>