<li class="post_activity_note note_item with_comment comment" id="comment_<?php echo $carovl['comment']['id']; ?>">
	<div class="post_activity_note_avatar">
		<a href="<?php echo $carovl['comment']['publisher']['url']; ?>" class="post_activity_avatar_link" title="<?php echo $carovl['comment']['publisher']['username']; ?>">
			<img src="<?php echo $carovl['comment']['publisher']['avatar']; ?>" alt="<?php echo $carovl['comment']['publisher']['username']; ?>">
		</a>
	</div>
	<div class="post_activity_note_content">
		<div class="note_content_inner">
			<p class="note_text">
				<a href="<?php echo $carovl['comment']['publisher']['url']; ?>" class="note_text_link">
					<?php echo $carovl['comment']['publisher']['username']; ?>
				</a>
				<?php if ($carovl['comment']['publisher']['verified'] == 1) { ?> 
				<span class="verified-user" data-toggle="tooltip" title="<?php echo $carovl['lang']['verified_user']; ?>">
					<i class="fa fa-check-circle"></i>
				</span>
				<?php } ?>
			</p>
			<p class="note_added_text">
				<?php echo $carovl['comment']['text']; ?>
				<span class="float-right pointer ml-2" id="like-comment" style="font-size: 12px; line-height: 1.5;" onclick="registerCommentLike(<?php echo $carovl['comment']['id']; ?>);">
					<?php if ($carovl['comment']['is_comment_liked'] === true) { ?> 
					<i class="fa fa-heart liked icon-loader"></i>
					<?php } else { ?> 
					<i class="fa fa-heart-o"></i>
					<?php } ?>
				</span>
				<?php if ($carovl['comment']['owner'] === true || $carovl['comment']['post_owner'] === true) { ?> 
				<span class="float-right ml-2 mr-2 delete-comment" style="color: #666;" data-show-hover="li" onclick="deleteComment(<?php echo $carovl['comment']['id']; ?>, <?php echo $carovl['story']['id']; ?>);">
					<i class="fa fa-trash icon-loader" data-icon="trash"></i>
				</span>
				<?php } ?>
			</p>
		</div>
	</div>
</li>
<script type="text/javascript">
(function ($) {

    var showHover = function () {
        $('[data-show-hover]').hide().each(function () {
            var self = $(this),
                parent = $(this).data('showHover');

            self.closest(parent).on('mouseover', function (e) {
                e.stopPropagation();
                self.show();
            }).on('mouseout', function () {
                self.hide();
            });
        });
    };
    showHover();
    window.showHover = showHover;
})(jQuery);
</script>