<meta property="og:title" content="<?php echo $carovl['story']['post_link_title']; ?>">
<meta property="og:type" content="article">
<meta property="og:image" content="<?php echo ($carovl['story']['post_link_image']); ?>">
<meta property="og:description" content="<?php echo $carovl['story']['post_link_content']; ?>">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="<?php echo $carovl['story']['post_link_title']; ?>">
<meta name="twitter:description" content="<?php echo $carovl['story']['post_link_content']; ?>">
<meta name="twitter:image" content="<?php echo ($carovl['story']['post_link_image']); ?>">