<meta property="og:title" content="<?php echo $carovl['title']; ?>">
<meta property="og:type" content="article">
<meta property="og:image" content="<?php echo getMedia($carovl['story']['post_file']); ?>">
<meta property="og:description" content="<?php echo $carovl['description']; ?>">
<meta name="twitter:title" content="<?php echo $carovl['title']; ?>">
<meta name="twitter:description" content="<?php echo $carovl['description']; ?>">
<meta name="twitter:image" content="<?php echo getMedia($carovl['story']['post_file']); ?>">