<div class="card setting">
	<?php echo loadPage('group-setting/header'); ?>
	<div class="card-block">
		<?php 
		$requests = getGroupRequests($carovl['setting']['group_id']);
		if (count($requests) > 0) {
			foreach ($requests as $carovl['request']) {
				echo loadPage('group-setting/join-requests/request-list');
			}
		} else { ?>
		<h5><?php echo $carovl['lang']['member_requests_not_found']; ?></h5>
		<?php }
		?>
	</div>
</div>