<?php 
$carovl['setting_page'] = 'general-setting';
$pages_array = array(
	'general-setting',
	'privacy-setting',
	'members',
	'join-requests',
);
if (! empty($_GET['tab'])) {
	if (in_array($_GET['tab'], $pages_array)) {
		$carovl['setting_page'] = $_GET['tab'];
	}
}
?>
<div class="col-md-10 offset-md-1">
	<div class="row">
		<div class="col-md-3">
			<?php echo loadPage('group-setting/control-section'); ?>
		</div>
		<div class="col-md-9">
			<?php echo loadPage('group-setting/' . $carovl['setting_page'] . '/content'); ?>
		</div>
	</div>
</div>
<script type="text/javascript">
function deleteGroup(group_id) {
	if (! group_id) {
		return false;
	} else {
		<?php 
		$confirmation = str_replace('{group_name}', $carovl['setting']['group_name'], $carovl['lang']['delete_group_confirmation']);
		?>
		swal({
			title: "<?php echo $confirmation; ?>",
			type: "warning",
			showCancelButton: true,
			confirmButtonColor: "#2CC990",
			confirmButtonText: "<?php echo $carovl['lang']['delete_label']; ?>",
			cancelButtonText: "<?php echo $carovl['lang']['nevermind_label']; ?>",
			showLoaderOnConfirm: true,
			closeOnConfirm: false,
		}, function () {
			$.get(ajaxRequests(), {
				f: 'groups',
				s: 'delete_group',
				group_id: group_id
			}, function (data) {
				if (data.status == 200) {
					<?php 
					$deleted = str_replace('{group_name}', $carovl['setting']['group_name'], $carovl['lang']['group_has_been_deleted']);
					?>
					swal({
						title: "<?php echo $deleted; ?>",
						type: "success",
						showConfirmButton: false
					});
					window.setTimeout(function() {
						window.location.href = data.href;
					}, 1000);
				}
			});
		});
	}
}
</script>