<div class="card-header">
	<div class="media">
		<a href="<?php echo $carovl['setting']['url']; ?>" data-redirect="?page=timeline&u=<?php echo $carovl['setting']['username']; ?>" id="updategroupname-<?php echo $carovl['setting']['group_id']; ?>">
			<img src="<?php echo $carovl['setting']['avatar']; ?>" alt="<?php echo $carovl['setting']['username']; ?>" class="d-flex mr-3">
		</a>
		<div class="media-body">
			<h5 class="mt-2">
				<a href="<?php echo $carovl['setting']['url']; ?>" data-redirect="?page=timeline&u=<?php echo $carovl['setting']['username']; ?>" id="updategroupname-<?php echo $carovl['setting']['group_id']; ?>" class="group_name">
					<?php echo $carovl['setting']['username']; ?>
				</a>
			</h5>
		</div>
	</div>
</div>