<div id="posts">
	<?php 
	$stories = getPosts(array(
		'limit' => 10
	));
	if (count($stories) <= 0) {
		echo loadPage('story/no-stories');
	} else {
		foreach ($stories as $carovl['story']) {
			echo loadPage('story/content');
		}
	}
	?>
</div>
<?php if (count($stories) > 0) { ?> 
<div class="card load-more">
	<div class="card-block">
		<div class="get-more-posts pointer" id="get-more-posts" onclick="getMorePosts();">
			<span>
				<i class="fa fa-repeat icon-loader" data-icon="repeat"></i>
			</span>
		</div>
	</div>
</div>
<?php } ?>