<div class="card admin mb-4">
	<div class="card-header">
		<h3 class="card-title"><?php echo $carovl['lang']['html_allowed']; ?></h3>
	</div>
	<div class="card-block">
		<form method="post" class="admin-announcement">
			<div class="form-group carovl">
				<textarea name="announcement_text" class="announcement-text form-control" dir="auto" rows="10"></textarea>
				<span class="highlight"></span>
				<span class="bar"></span>
				<label><?php echo $carovl['lang']['new_announcement']; ?></label>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-carovl">
					<i class="fa fa-plus icon-loader" data-icon="plus"></i> <?php echo $carovl['lang']['add_label']; ?>
				</button>
			</div>
		</form>
	</div>
</div>
<div class="card admin mb-4">
	<div class="card-header">
		<h3 class="card-title"><?php echo $carovl['lang']['active_announcements']; ?></h3>
	</div>
	<div class="card-block active-announcements announcements">
		<?php 
		$active_announcements = getActiveAnnouncements();
		if (count($active_announcements) == 0) {
			echo '<div class="text-center no-active-announcements"><h4>' . $carovl['lang']['active_announcements_not_found'] . '</h4></div>';
		} else {
			foreach ($active_announcements as $carovl['active_announcement']) {
				echo loadPage('admin/announcement/active-list');
			}
		}
		?>
	</div>
</div>
<div class="card admin mb-4">
	<div class="card-header">
		<h3 class="card-title"><?php echo $carovl['lang']['inactive_announcements']; ?></h3>
	</div>
	<div class="card-block inactive-announcements announcements">
		<?php 
		$inactive_announcements = getInactiveAnnouncements();
		if (count($inactive_announcements) == 0) {
			echo '<div class="text-center no-inactive-announcements"><h4>' . $carovl['lang']['inactive_announcements_not_found'] . '</h4></div>';
		} else {
			foreach ($inactive_announcements as $carovl['inactive_announcement']) {
				echo loadPage('admin/announcement/inactive-list');
			}
		}
		?>
	</div>
</div>
<script type="text/javascript">
$(function () {
	autosize($('textarea.announcement-text'));
	$('form.admin-announcement').ajaxForm({
		url: ajaxRequests() + '?f=admin_setting&s=add_new_announcement',
		beforeSend: function () {
			progressLoader($('form.admin-announcement').find('button'));
			$('form.admin-announcement').find('button').attr('disabled', true);
		},
		success: function (data) {
			if (data.status == 200) {
				$('.no-active-announcements').slideUp(300);
				$('form.admin-announcement').clearForm();
				$('textarea').removeClass('used');
				$('.active-announcements').prepend(data.html);
			}
			progressLoader($('form.admin-announcement').find('button'));
			$('form.admin-announcement').find('button').attr('disabled', false);
		}
	});
});
function deleteAnnouncement(id) {
	var announcement_wrapper = $('.announcements').find('.announcement-' + id);
	$.get(ajaxRequests(), {
		f: 'admin_setting',
		s: 'delete_announcement',
		id: id
	}, function (data) {
		if (data.status == 200) {
			announcement_wrapper.slideUp(300, function () {
				$(this).remove();
			});
			swal({
				title: "<?php echo $carovl['lang']['announcement_deleted']; ?>",
				type: "success",
				confirmButtonColor: "#2CC990",
			});
			if (data.count_active == 0) {
				$('.active-announcements').slideDown(300, function () {
					$(this).html('<div class="text-center no-active-announcements"><h4><?php echo $carovl['lang']['active_announcements_not_found']; ?></h4></div>');
				});
			}
			if (data.count_inactive == 0) {
				$('.inactive-announcements').slideDown(300, function () {
					$(this).html('<div class="text-center no-inactive-announcements"><h4><?php echo $carovl['lang']['inactive_announcements_not_found']; ?></h4></div>');
				});
			}
		}
	});
}
function disableAnnouncement(id) {
	var announcement_wrapper = $('.active-announcements').find('.announcement-' + id);
	var inactive_announcement_wrapper = $('.inactive-announcements');
	$.get(ajaxRequests(), {
		f: 'admin_setting',
		s: 'disable_announcement',
		id: id
	}, function (data) {
		if (data.status == 200) {
			announcement_wrapper.slideUp(300, function () {
				$(this).remove();
			});
			swal({
				title: "<?php echo $carovl['lang']['announcement_disabled']; ?>",
				type: "success",
				confirmButtonColor: "#2CC990",
			});
			if (data.count == 0) {
				$('.active-announcements').slideDown(300, function () {
					$(this).html('<div class="text-center no-active-announcements"><h4><?php echo $carovl['lang']['active_announcements_not_found']; ?></h4></div>');
				});
			}
			if (data.html.length != 0) {
				$('.no-inactive-announcements').slideUp(300);
				inactive_announcement_wrapper.prepend(data.html);
			}
		}
	});
}
function enableAnnouncement(id) {
	var announcement_wrapper = $('.inactive-announcements').find('.announcement-' + id);
	var active_announcement_wrapper = $('.active-announcements');
	$.get(ajaxRequests(), {
		f: 'admin_setting',
		s: 'enable_announcement',
		id: id
	}, function (data) {
		if (data.status == 200) {
			$('.no-active-announcements').slideUp(300);
			announcement_wrapper.slideUp(200, function () {
				$(this).remove();
			});
			swal({
				title: "<?php echo $carovl['lang']['announcement_enabled']; ?>",
				type: "success",
				confirmButtonColor: "#2CC990",
			});
			if (data.count_inactive == 0) {
				$('.inactive-announcements').slideDown(300, function () {
					$(this).html('<div class="text-center no-inactive-announcements"><h4><?php echo $carovl['lang']['inactive_announcements_not_found']; ?></h4></div>');
				});
			}
			if (data.html.length != 0) {
				active_announcement_wrapper.prepend(data.html);
			}
		}
	});
}
</script>