<div class="post-wrapper">
	<div class="post-user" id="post-<?php echo $carovl['story']['id']; ?>" data-post-id="<?php echo $carovl['story']['id']; ?>">
		<?php if (empty($carovl['page'])) { $carovl['page'] = 'home'; } ?>

		<?php if ($carovl['story']['via_type'] == 'share') { ?> 
		<?php 
		$shared_post = str_replace('{username}', $carovl['story']['via']['username'], $carovl['lang']['shared_this_post']);
		?>
		<div class="card shared-info">
			<div class="card-header">
				<h5 class="card-title"><?php echo $shared_post; ?></h5>
			</div>
		</div>
		<?php } ?>

		<div class="card story">
			<h4 class="card-header">
				<div class="media">
					<a href="<?php echo $carovl['story']['publisher']['url']; ?>" data-redirect="?page=timeline&u=<?php echo $carovl['story']['publisher']['username']; ?>">
						<img src="<?php echo $carovl['story']['publisher']['avatar']; ?>" alt="<?php echo $carovl['story']['publisher']['username']; ?>" id="useravatar-<?php echo $carovl['story']['publisher']['user_id']; ?>" class="d-flex mr-3">
					</a>
					<div class="media-body">
						<?php if ($carovl['logged_in'] == true) { ?>
						<div class="float-right">
							<ul class="dropdown">
								<span class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
									<i class="fa fa-ellipsis-h"></i>
								</span>
								<li class="dropdown-menu post-options">
									<?php if ($carovl['story']['admin'] === true || $carovl['story']['group_admin'] === true) { ?> 
									<?php echo loadPage('story/post-owner'); ?>
									<?php } elseif ($carovl['logged_in'] == true) { ?> 
									<a class="dropdown-item pointer save-post" onclick="savePost(<?php echo $carovl['story']['id']; ?>);">
										<?php if ($carovl['story']['is_post_saved'] == true) { ?> 
										<i class="fa fa-bookmark icon-loader saved" data-icon="bookmark"></i> <?php echo $carovl['lang']['unsave_post']; ?>
										<?php } else { ?> 
										<i class="fa fa-bookmark-o icon-loader" data-icon="bookmark-o"></i> <?php echo $carovl['lang']['save_post']; ?>
										<?php } ?>
									</a>
									<a class="pointer dropdown-item report-post" onclick="reportPost(<?php echo $carovl['story']['id']; ?>);">
										<?php if ($carovl['story']['is_post_reported'] === true) { ?> 
										<i class="fa fa-flag icon-loader reported" data-icon="flag"></i> <?php echo $carovl['lang']['unreport_post']; ?>
										<?php } else { ?> 
										<i class="fa fa-flag-o icon-loader" data-icon="flag-o"></i> <?php echo $carovl['lang']['report_post']; ?>
										<?php } ?>
									</a>
									<?php 
									$link = $carovl['story']['url'];
									$open = $carovl['lang']['open_post_in_new_tab'];
									if (! empty($carovl['story']['article_id'])) {
										$link = $carovl['story']['article']['url'];
										$open = $carovl['lang']['open_article'];
									}
									if (! empty($carovl['story']['product_id'])) {
										$link = $carovl['story']['product']['url'];
									}
									?>
									<a href="<?php echo $link; ?>" class="dropdown-item" target="_blank">
										<i class="fa fa-link icon-loader" data-icon="link"></i> <?php echo $open; ?>
									</a>
									<?php } ?>
								</li>
							</ul>
						</div> 
						<?php } ?>
						<div class="username">
							<span class="user-preview" data-type="<?php echo $carovl['story']['publisher']['type']; ?>" data-id="<?php echo $carovl['story']['publisher']['id']; ?>">
								<a href="<?php echo $carovl['story']['publisher']['url']; ?>" data-redirect="?page=timeline&u=<?php echo $carovl['story']['publisher']['username']; ?>">
									<?php echo $carovl['story']['publisher']['username']; ?>
								</a>
							</span>
							<?php if ($carovl['story']['publisher']['verified'] == 1) { ?> 
							<span class="verified-user" data-toggle="tooltip" title="<?php echo $carovl['lang']['verified_user']; ?>">
								<i class="fa fa-check-circle"></i>
							</span>
							<?php } ?>
							<?php 
							if ($carovl['story']['post_type'] == 'profile_picture') {
								$avatar_changed_lang = $carovl['lang']['profile_picture_changed_male'];
								if ($carovl['story']['publisher']['gender'] == 'female') {
									$avatar_changed_lang = $carovl['lang']['profile_picture_changed_female'];
								} else {
									$avatar_changed_lang = $carovl['lang']['profile_picture_changed_male'];
								}
								?>
								<span class="post-info">
									<?php echo $avatar_changed_lang; ?>
								</span>
							<?php } ?>
							<?php 
							if ($carovl['story']['post_type'] == 'profile_cover_picture') {
								$cover_changed_lang = $carovl['lang']['profile_cover_picture_changed_male'];
								if ($carovl['story']['publisher']['gender'] == 'female') {
									$cover_changed_lang = $carovl['lang']['profile_cover_picture_changed_female'];
								} else {
									$cover_changed_lang = $carovl['lang']['profile_cover_picture_changed_male'];
								}
								?>
								<span class="post-info">
									<?php echo $cover_changed_lang; ?>
								</span>
							<?php } ?>
							<?php if (! empty($carovl['story']['product_id'])) { ?> 
							<span class="post-info"><?php echo $carovl['lang']['added_new_product']; ?></span>
							<?php } ?>
							<?php if (! empty($carovl['story']['article_id'])) { ?> 
							<span class="post-info">
								<?php echo $carovl['lang']['writing_an_article']; ?>
							</span>
							<?php } ?>
							<?php if (! empty($carovl['story']['event_id']) && empty($carovl['story']['post_text'])) { ?> 
							<span class="post-info">
								<?php echo $carovl['lang']['created_new_event']; ?>
							</span>
							<?php } elseif (! empty($carovl['story']['event_id']) && ! empty($carovl['story']['post_text']) && $carovl['page'] != 'events') { ?> 
							<span class="post-info">
								<?php echo $carovl['lang']['posted_on']; ?> <a href="<?php echo $carovl['story']['event']['url']; ?>" data-redirect="?page=view-event&id=<?php echo $carovl['story']['event']['id']; ?>">
									<?php echo $carovl['story']['event']['name']; ?>
								</a>
							</span>
							<?php } ?>
							<div class="time">
								<i class="fa fa-clock-o"></i>
								<span class="ajax-time" title="<?php echo date('c', $carovl['story']['time']); ?>">
									<?php echo timeElapsedString($carovl['story']['time']); ?>
								</span>
								<?php if (! empty($carovl['story']['post_map'])) { ?> 
								&nbsp;-&nbsp;
								<span class="post-info">
									<i class="fa fa-map-marker"></i> <?php echo $carovl['story']['post_map']; ?>
								</span>
								<?php } ?>
							</div>
						</div>
					</div>
				</div>
			</h4>
			<div class="card-block">
				<?php if (! empty($carovl['story']['post_map']) && empty($carovl['story']['post_text']) && empty($carovl['story']['post_file'])) { ?> 
				<div class="post-map">
					<img src="https://maps.googleapis.com/maps/api/staticmap?center=<?php echo $carovl['story']['post_map'];?>&zoom=13&size=600x250&maptype=roadmap&markers=color:red%7C<?php echo $carovl['story']['post_map'];?>&key=<?php echo $carovl['config']['google_map_api'];?>">
				</div>
				<?php } ?>
				<?php if (! empty($carovl['story']['event_id']) && empty($carovl['story']['post_text'])) { ?> 
				<div class="post-file">
					<a href="<?php echo $carovl['story']['event']['url']; ?>" data-redirect="?page=view-event&id=<?php echo $carovl['story']['event']['id']; ?>">
						<img src="<?php echo $carovl['story']['event']['cover']; ?>" alt="<?php echo $carovl['story']['event']['name']; ?>" class="img-fluid" id="event-cover">
					</a>
				</div>
				<div class="post-text-content">
					<div class="event-name">
						<i class="fa fa-calendar-o"></i> <a href="<?php echo $carovl['story']['event']['url']; ?>" data-redirect="?page=view-event&id=<?php echo $carovl['story']['event']['id']; ?>">
							<?php echo $carovl['story']['event']['name']; ?>
						</a>
					</div>
					<div class="event-description">
						<?php echo $carovl['story']['event']['description']; ?>
					</div>
					<div class="event-time">
						<?php echo $carovl['story']['event']['event_time']; ?>
					</div>
				</div>
				<iframe src="https://www.google.com/maps/embed/v1/place?key=<?php echo $carovl['config']['google_map_api']; ?>&q=<?php echo $carovl['story']['event']['location']; ?>" width="100%" frameborder="0" style="border: 0;"></iframe>
				<?php } ?>
				<?php if (! empty($carovl['story']['product_id'])) { ?> 
				<div class="post-product has_product_post">
					<div class="post-file">
						<?php
						if (count($carovl['story']['product']['images']) == 1) { ?>
							<img src="<?php echo $carovl['story']['product']['images'][0]['image']; ?>" alt="<?php echo $carovl['story']['product']['name']; ?>" class="img-fluid" onclick="openImageAlbum(<?php echo $carovl['story']['product']['images'][0]['id']; ?>, 'product');">
						<?php } else { ?>
							<div id="product-carousel-<?php echo $carovl['story']['product_id']; ?>" class="carousel slide" data-ride="carousel">
								<ol class="carousel-indicators">
									<?php for ($i = 0; $i < count($carovl['story']['product']['images']); $i++) { ?>
									<li data-target="#product-carousel-<?php echo $carovl['story']['product_id']; ?>" data-slide-to="<?php echo $i; ?>" <?php echo ($i == 0) ? 'class="active"' : ''; ?>></li>
									<?php } ?>
								</ol>
								<div class="carousel-inner" role="listbox">
									<?php 
									$i = 0;
									foreach ($carovl['story']['product']['images'] as $image) { ?>
										<div class="carousel-item <?php echo ($i == 0) ? 'active' : ''; ?>">
											<img class="d-block img-fluid" src="<?php echo $image['image_org']; ?>" alt="<?php echo $carovl['story']['product']['name']; ?>" onclick="openImageAlbum(<?php echo $image['id']; ?>, 'product');">
										</div>
									<?php $i++; }
									?>
								</div>
								<a class="carousel-control-prev" href="#product-carousel-<?php echo $carovl['story']['product_id']; ?>" role="button" data-slide="prev">
									<span class="carousel-control-prev-icon" aria-hidden="true"></span>
									<span class="sr-only">Previous</span>
								</a>
								<a class="carousel-control-next" href="#product-carousel-<?php echo $carovl['story']['product_id']; ?>" role="button" data-slide="next">
									<span class="carousel-control-next-icon" aria-hidden="true"></span>
									<span class="sr-only">Next</span>
								</a>
							</div>
						<?php } ?>
					</div>
					<div class="post-text-content">
						<h3 class="product-name">
							<?php echo $carovl['story']['product']['name']; ?>
						</h3>
						<div class="product-description mb-2"><?php echo $carovl['story']['product']['description']; ?></div>
						<div class="product-status float-right">
							<h5>
							<?php
							$status = ($carovl['story']['product']['status'] == 0) ? '<span class="product-in-stock" id="product-status">' . $carovl['lang']['in_stock'] . '</span>' : '<span class="product-sold" id="product-status">' . $carovl['lang']['sold'] . '</span>';
							echo $status;
							?>
							</h5>
						</div>
						<div class="product-type">
							<h5>
							<?php
							$type = ($carovl['story']['product']['type'] == 0) ? '<span class="new">' . $carovl['lang']['new_label'] . '</span>' : '<span>' . $carovl['lang']['used_label'] . '</span>';
							echo $type;
							?>
							</h5>
						</div>
						<div class="product-price">
							<h3>
								<?php echo $carovl['story']['product']['price']; ?>
							</h3>
						</div>
						<div class="product-location">
							<i class="fa fa-map-marker"></i> <?php echo $carovl['story']['product']['location']; ?>
						</div>
					</div>
				</div>
				<?php } ?>
				<?php if (! empty($carovl['story']['article_id'])) { ?>
				<div class="post-file">
					<img src="<?php echo $carovl['story']['article']['thumbnail']; ?>" alt="<?php echo $carovl['story']['article']['article_title']; ?>" class="img-fluid">
				</div>
				<div class="post-text-content">
					<div class="article-title">
						<a href="<?php echo $carovl['story']['article']['url']; ?>" data-redirect="?page=article&id=<?php echo $carovl['story']['article_id']; ?>">
							<?php echo $carovl['story']['article']['article_title']; ?>
						</a>
					</div>
					<div class="article-content">
						<?php 
						$article_content = htmlspecialchars_decode($carovl['story']['article']['article_content']);
						if (strlen($article_content) > 200) {
							echo mb_substr($article_content, 0, 100) . ' <a href="' . $carovl['story']['article']['url'] . '" data-redirect="?page=article&id=' . $carovl['story']['article_id'] . '">' . $carovl['lang']['read_more'] . '</a>';
						} else {
							echo $article_content;
						}
						?>
					</div>
					<div class="article-tags">
						<?php echo $carovl['lang']['tags']; ?>:
						<?php
						if (is_array($carovl['story']['article']['tags'])) {
							foreach ($carovl['story']['article']['tags'] as $key => $tag) { ?>
								<a href="<?php echo seoLink('index.php?page=hashtag&hash=' . $tag); ?>">
									<?php echo '#' . $tag; ?>
								</a>
							<?php }
						}
						?>
						<?php if (! empty($carovl['story']['article']['article_source'])) { ?>
						<span class="float-right article-source">
							<?php echo $carovl['lang']['source_label']; ?>: <a href="<?php echo $carovl['story']['article']['article_source']; ?>" target="_blank">
								<?php 
								$source = parse_url($carovl['story']['article']['article_source']);
								echo $source['host'];
								?>
							</a>
						</span>
						<?php } ?>
					</div>
				</div>
				<?php } ?>
				<?php if (! empty($carovl['story']['post_file'])) { ?> 
				<div class="post-file">
					<?php 
					$media = array(
						'type' => 'post',
						'story_id' => $carovl['story']['id'],
						'filename' => $carovl['story']['post_file'],
						'name' => $carovl['story']['post_file_name'],
						'alt' => $carovl['story']['publisher']['username']
					);
					echo displaySharedFile($media);
					?>
				</div>
				<?php } ?>
				<?php if (! empty($carovl['story']['post_link']) && empty($carovl['story']['post_file'])) { ?> 
				<div class="post-link has_url_post">
					<a href="<?php echo $carovl['story']['post_link']; ?>" target="_blank">
						<?php if (! empty($carovl['story']['post_link_image'])) { ?> 
						<div class="post-file">
							<img src="<?php echo $carovl['story']['post_link_image']; ?>" class="img-fluid" alt="<?php echo $carovl['story']['post_link_title']; ?>">
						</div>
						<?php } ?>
						<div class="post-text-content">
							<h4 class="url-title">
								<?php echo $carovl['story']['post_link_title']; ?>
							</h4>
							<div class="url-description"><?php echo $carovl['story']['post_link_content']; ?></div>
							<div class="post-url">
								<?php 
								$url = parse_url($carovl['story']['post_link']);
								echo $url['host'];
								?>
							</div>
						</div>
					</a>
				</div>
				<?php } ?>
				<div class="post-text-content <?php echo (! empty($carovl['story']['post_text']) && empty($carovl['story']['article_id'])) ? 'has_text' : 'no_text'; ?>">
					<p dir="auto" class="text-content">
						<?php if (! empty($carovl['story']['post_text']) && empty($carovl['story']['article_id'])) { ?> 
								<?php echo $carovl['story']['post_text']; ?>
						<?php } ?>
					</p>
				</div>
			</div>
			<div class="card-footer">
				<span class="post-notes" onclick="openPostActivity(<?php echo $carovl['story']['id']; ?>);">
					<span id="notes">
					<?php 
					if (countPostNotes($carovl['story']['id']) == 1) {
						echo countPostNotes($carovl['story']['id']) . ' ' . $carovl['lang']['note'];
					} elseif (countPostNotes($carovl['story']['id']) > 1) {
						echo countPostNotes($carovl['story']['id']) . ' ' . $carovl['lang']['notes'];
					} else {
						echo "";
					}
					?>
					</span>
				</span>
				<?php if ($carovl['logged_in'] == true) { ?> 
				<span class="interact-button float-right">
					<span data-toggle="tooltip" title="<?php echo $carovl['lang']['like']; ?>" id="love-button" onclick="registerLike(<?php echo $carovl['story']['id']; ?>);">
						<?php  
						$icon = 'fa-heart-o';
						$class = '';
						if ($carovl['story']['is_post_liked'] === true) {
							$icon = 'fa-heart';
							$class = 'has_liked';
						}
						?>
						<i class="fa <?php echo $icon; ?> <?php echo $class; ?>"></i>
					</span>
					<span onclick="openPostActivity(<?php echo $carovl['story']['id']; ?>);" data-toggle="tooltip" title="<?php echo $carovl['lang']['comments']; ?>">
						<i class="fa fa-comment-o"></i>
					</span>
					<span data-toggle="tooltip" title="<?php echo $carovl['lang']['share']; ?>" onclick="openShareButtons(<?php echo $carovl['story']['id']; ?>);">
						<i class="fa fa-share-alt"></i>
					</span>
					<?php if (! empty($carovl['story']['post_file']) && strpos($carovl['story']['post_file'], '_video') !== false) { ?> 
					<span data-video-id="<?php echo $carovl['story']['id']; ?>">
						<?php 
						$views = countVideoViews($carovl['story']['id']);
						echo strtolower($views['views']);
						?>
					</span>
					<?php } ?>
				</span>
				<?php } ?>
			</div>
			<div class="card share">
				<div class="card-block">
					<?php if ($carovl['story']['admin'] === false && $carovl['story']['group_recipient_exist'] === false && ($carovl['story']['post_type'] != 'profile_picture' || $carovl['post_type'] != 'profile_cover_picture')) { ?> 
					<span class="btn social-btn <?php echo isPostShared($carovl['story']['id'], $carovl['user']['user_id']) ? 'btn-carovl is_shared pointer' : 'btn-white'; ?>" onclick="registerShare(<?php echo $carovl['story']['id']; ?>);" id="share_<?php echo $carovl['story']['id']; ?>">
						<i class="fa fa-share-alt fa-fw"></i>
					</span>
					<?php } ?>
					<a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $carovl['story']['url']; ?>" class="btn social-btn btn-facebook" target="_blank">
						<i class="fa fa-facebook fa-fw"></i>
					</a>
					<a href="https://twitter.com/intent/tweet?text=<?php echo $carovl['story']['url']; ?>" class="btn social-btn btn-twitter" target="_blank">
						<i class="fa fa-twitter fa-fw"></i>
					</a>
					<a href="https://plus.google.com/share?url=<?php echo $carovl['story']['url']; ?>" class="btn social-btn btn-google" target="_blank">
						<i class="fa fa-google-plus fa-fw"></i>
					</a>
				</div>
			</div>
		</div>
		<?php
		if ($carovl['logged_in'] == true) {
			echo loadPage('modals/post-activity');
			echo loadPage('modals/delete-post');
			echo loadPage('modals/edit-post');
		} 
		?>
	</div>
</div>
<script type="text/javascript">
(function ($) {

    var showHover = function () {
        $('[data-show-hover]').hide().each(function () {
            var self = $(this),
                parent = $(this).data('showHover');

            self.closest(parent).on('mouseover', function (e) {
                e.stopPropagation();
                self.show();
            }).on('mouseout', function () {
                self.hide();
            });
        });
    };
    showHover();
    window.showHover = showHover;
})(jQuery);
$(function () {
	$('#post-<?php echo $carovl['story']['id']; ?> #post-activity .comment-input').triggeredAutocomplete({
		hidden: '#hidden_mention_comment',
		source: ajaxRequests() + '?f=mention',
		trigger: '@'
	});
	$('.dropdown-menu.post-options').click(function (e) {
		e.stopPropagation();
	});
});
</script>