<div class="card story">
	<form action="#" method="post" class="post textbox">
		<div class="card-block">
			<div id="image-preview" class="preview-image"></div>
			<div id="post-textarea">
				<i class="fa fa-spinner fa-spin" id="loader-publisher"></i>
				<textarea name="post_text" class="form-control post_text" placeholder="<?php echo $carovl['lang']['share_anything']; ?>" dir="auto"></textarea>
			</div>
			<?php if ($carovl['config']['file_sharing'] == 1) { ?> 
			<div class="hidden-input" id="file-form">
				<div class="inner-addon left-addon">
					<i class="fa fa-file"></i>
					<input type="text" name="filename" class="form-control" readonly>
				</div>
			</div>
			<?php } ?>
			<?php if ($carovl['config']['video_upload'] == 1) { ?> 
			<div class="hidden-input" id="video-form">
				<div class="inner-addon left-addon">
					<i class="fa fa-video-camera"></i>
					<input type="text" name="video-name" class="form-control" readonly>
				</div>
			</div>
			<?php } ?>
			<?php if ($carovl['config']['audio_upload'] == 1) { ?> 
			<div class="hidden-input" id="music-form">
				<div class="inner-addon left-addon">
					<i class="fa fa-music"></i>
					<input type="text" name="music-name" class="form-control" readonly>
				</div>
			</div>
			<?php } ?>
			<div class="hidden-input" id="map-form">
				<div class="inner-addon left-addon">
					<i class="fa fa-map-marker"></i>
					<input type="text" name="post_map" id="search-field" class="form-control" placeholder="<?php echo $carovl['lang']['maps_placeholder']; ?>">
				</div>
			</div>
			<div id="results"></div>
			<div id="progress">
				<span id="percent">
					0%
				</span>
				<div class="progress">
					<div id="bar" class="progress-bar bg-carovl"></div>
				</div>
			</div>
		<div class="card-footer">
			<div class="tools float-left">
				<span onclick="getElementById('post-photos').click()";">
					<i class="fa fa-camera"></i>
					<input type="file" name="post_photos[]" accept="image/*" class="hidden-input" id="post-photos">
				</span>
				<?php if ($carovl['config']['video_upload'] == 1) { ?>
				<span onclick="getElementById('post-video').click();;">
					<i class="fa fa-video-camera"></i>
					<input type="file" name="post_video" class="hidden-input" id="post-video" accept="video/*">
				</span>
				<?php } ?>
				<?php if ($carovl['config']['audio_upload'] == 1) { ?> 
				<span onclick="getElementById('post-music').click();">
					<i class="fa fa-music"></i>
					<input type="file" name="post_music" class="hidden-input" accept="audio/*" id="post-music">
				</span>
				<?php } ?>
				<?php if ($carovl['config']['file_sharing'] == 1) { ?> <span onclick="getElementById('post-file').click();">
					<i class="fa fa-file"></i>
					<input type="file" name="post_file" id="post-file" class="hidden-input">
				</span>
				<?php } ?>
				<span id="emoticon-btn">
					<i class="fa fa-smile-o"></i>
				</span>
				<span id="map-btn">
					<i class="fa fa-map-marker"></i>
				</span>
				<span>
					<span id="characters-left"></span>
				</span>
				<input type="hidden" name="group_id" value="<?php echo $carovl['group_profile']['id']; ?>">
				<input type="hidden" name="hash_id" value="<?php echo createSession(); ?>">
			</div>
			<div class="float-right">
				<button class="btn btn-carovl btn-post" type="submit" id="post-button">
					<i class="fa fa-pencil icon-loader" data-icon="pencil"></i> <?php echo strtoupper($carovl['lang']['post_label']); ?>
				</button>
			</div>
		</div>
		<div class="emoticon_container">
			<div class="emoticon_wrapper">
				<?php 
				foreach ($carovl['emoticons'] as $code => $name) {
					$code = $code;
					echo  '<span onclick="addEmoticon(\'' . $code . '\',\'#post-textarea textarea\');"><i class="pointer twa-lg twa twa-' . $name . '"></i></span>';
				}
				?>
			</div>
		</div>
	</form>
</div>
<div id="user-mention"></div>
<script type="text/javascript">
$(function () {
	$('.modal.textbox').find('.close').click(function () {
		$('#photo-form, #video-form, #file-form, #map-form, #music-form, .emoticon_container').slideUp(100);
		$('form.post').clearForm();
		$('#image-preview').hide();
		$('.post_text').attr('placeholder', '<?php echo $carovl['lang']['share_anything']; ?>');
	});
	$('.post_text').triggeredAutocomplete({
		hidden: '#user-mention',
		source: ajaxRequests() + '?f=mention',
		trigger: '@'
	});
	autosize($('textarea.post_text'));
	$('#emoticon-btn').click(function () {
		$('.emoticon_container').fadeToggle(100);
	});
	$('#post-file').change(function () {
		var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
		$('#file-form input').val(filename);
		$('#file-form').fadeToggle(100);
	});
	$('#post-video').change(function () {
		var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
		$('#video-form input').val(filename);
		$('#video-form').fadeToggle(100);
	});
	$('#post-music').change(function () {
		var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
		$('#music-form input').val(filename);
		$('#music-form').fadeToggle(100);
	});
	$('#post-photos').change(function () {
		$('#image-preview').show('fast');
		$('#image-preview').html('<img src="' + window.URL.createObjectURL(this.files[0]) + '"><div class="close-image" onclick="closePreview();"><i class="fa fa-times"></i></div>');
		$('.post_text').attr('placeholder', '<?php echo $carovl['lang']['add_caption']; ?>');
	});
	$('#map-btn').click(function () {
		$('#map-form').fadeToggle(100);
	});
	<?php if ($carovl['config']['max_characters'] != 10000) { ?> 
	$('textarea').limit('<?php echo $carovl['config']['max_characters']; ?>', '#characters-left');
	<?php } ?>

	var bar = $('#bar');
	var percent = $('#percent');
	var post_button = $('#post-button');

	$('form.post').ajaxForm({
		url: ajaxRequests() + '?f=posts&s=new_post',
		beforeSend: function () {
			var percentVal = '0%';
			bar.width(percentVal);
			percent.html(percentVal);
			post_button.attr('disabled', true);
			progressLoader(post_button);
		},
		uploadProgress: function (event, position, total, percentComplete) {
			var percentVal =  percentComplete + '%';
			bar.width(percentVal);
			$('#progress').slideDown(100);
			if (percentComplete > 50) {
				percent.addClass('white');
			}
			percent.html(percentVal);
		},
		success: function (data) {
			var text_box = $('body').find('#post-textbox-<?php echo $carovl['user']['user_id']; ?>');
			$('#progress').slideUp(100);
			post_button.attr('disabled', false);
			percent.removeClass('white');
			$('.post_text').css('height', 'auto');
			$('#image-preview').hide('fast');
			$('.post_text').attr('placeholder', '<?php echo $carovl['lang']['share_anything']; ?>');
			if (data.status == 200) {
				if (data.html.length > 0) {
					$('#posts, #hashtag-posts').find('.posts-container').remove();
				}
				$('#posts, #hashtag-posts').prepend(data.html);
				$('#photo-form, #video-form, #file-form, #map-form, #music-form, .emoticon_container').slideUp(100);
				$('form.post').clearForm();
				<?php if ($carovl['config']['max_characters'] != 100000) { ?> 
				$('#charsleft').text("<?php echo $carovl['config']['max_characters']; ?>");
				<?php } ?>
				text_box.modal('hide');
			}
			progressLoader(post_button);
		}
	});
	var pac_input = document.getElementById('search-field');
	(function pacSelectFirst(input) {
		var _addEventListener = (input.addEventListener) ? input.addEventListener : input.attachEvent;
		function addEventListenerWrapper(type, listener) {
			if (type == "keydown") {
				var org_listener = listener;
				listener = function (event) {
					var suggestion_selected = $('.pac-item-selected').length > 0;
					if (event.which == 13 && ! suggestion_selected) {
						var simulated_downarrow = $.Event("keydown", {
							keyCode: 40,
							which: 40
						});
						org_listener.apply(input, [simulated_downarrow]);
					}
					org_listener.apply(input, [event]);
				};
			}
			_addEventListener.apply(input, [type, listener]);
		}
		if (input.addEventListener) {
			input.addEventListener = addEventListenerWrapper;
		} else if (input.attachEvent) {
			input.attachEvent = addEventListenerWrapper;
		}
	})(pac_input);
	$(function () {
		var autocomplete = new google.maps.places.Autocomplete(pac_input);
	});
});
function closePreview() {
	$('#image-preview').hide('fast');
	$('#post-photos').replaceWith($('#post-photos').val('').clone(true));
	$('.post_text').attr('placeholder', '<?php echo $carovl['lang']['share_anything']; ?>');
}
</script>