<div class="card admin">
	<div class="card-block">
		<div class="table-responsive">
			<table class="table table-hover table-condensed">
				<thead>
					<tr>
						<th><?php echo $carovl['lang']['id']; ?></th>
						<th><?php echo $carovl['lang']['author']; ?></th>
						<th><?php echo $carovl['lang']['event']; ?></th>
						<th><?php echo $carovl['lang']['time']; ?></th>
						<th><?php echo $carovl['lang']['action']; ?></th>
					</tr>
				</thead>
				<tbody class="result event-list">
					<?php 
					$events = getAllEvents(array(
						'limit' => 10,
					));
					if (count($events) > 0) {
						foreach ($events as $carovl['event']) {
							echo loadPage('admin/events/event-list');
						}
					}
					?>
				</tbody>
			</table>
		</div>
		<input type="hidden" name="hash_id" id="hash_id" value="<?php echo createSession(); ?>">
		<?php if (count($events) == 0) { ?> 
		<div class="view-more-wrapper view-more-articles">
			<span class="text-center btn btn-white">
				<?php echo $carovl['lang']['no_data']; ?>
			</span>
		</div>
		<?php } elseif (count($events) >= 10) { ?> 
		<div class="view-more-wrapper view-more-events">
			<span class="text-center btn btn-white" onclick="getMoreEvents();">
				<i class="fa fa-arrow-down icon-loader" data-icon="arrow-down"></i> <?php echo $carovl['lang']['show_more_events']; ?>
			</span>
		</div>
		<?php } ?>
	</div>
</div>
<script type="text/javascript">
<?php if (count($events) >= 10) { ?>
function getMoreEvents() {
	view_more_wrapper = $('.view-more-events');
	after_event_id = $('.event-list').find('.list:last').attr('data-event-id');
	progressLoader(view_more_wrapper.find('.btn-white'));
	$.get(ajaxRequests() + '?f=admin_setting&s=get_more_events', {
		after_event_id: after_event_id
	}, function (data) {
		if (data.html.length != 0) {
			$('tbody.result').append(data.html);
		} else {
			view_more_wrapper.html('<span class="text-center btn btn-white" onclick="getMoreEvents();"><?php echo $carovl['lang']['no_more_events']; ?></span>').fadeOut('slow');
		}
		progressLoader(view_more_wrapper.find('.btn-white'));
	});
}
<?php } ?>
function deleteEventAdmin(event_id) {
	hash_id = $('#hash_id').val();
	swal({
		title: "<?php echo $carovl['lang']['delete_event_confirmation']; ?> <?php echo $carovl['lang']['id']; ?>: " + event_id,
		type: "warning",
		showCancelButton: true,
		confirmButtonColor: "#2CC990",
		confirmButtonText: "<?php echo $carovl['lang']['delete_label']; ?>",
		cancelButtonText: "<?php echo $carovl['lang']['nevermind_label']; ?>",
		showLoaderOnConfirm: true,
		closeOnConfirm: false,
	}, function () {
		$.get(ajaxRequests(), {
			f: 'admin_setting',
			s: 'delete_event',
			event_id: event_id,
			hash_id: hash_id
		}, function (data) {
			if (data.status == 200) {
				$('#event_id_' + event_id).fadeOut(300, function () {
					$(this).remove();
				});
				swal.close();
			}
		});
	});
}
</script>