<li class="dropdown-item result">
	<span class="user-preview" data-id="<?php echo $carovl['result']['id']; ?>" data-type="<?php echo $carovl['result']['type']; ?>" data-placement="search">
		<a href="<?php echo $carovl['result']['url'] . $carovl['marker']; ?>ref=se" data-redirect="?page=timeline&u=<?php echo $carovl['result']['username']; ?>&ref=se">
			<div class="media">
				<div class="media-body">
					<h6 class="mt-0 mb-0 search-username">
						<?php echo $carovl['result']['username']; ?>
						<?php if (empty($carovl['result']['group_id'])) { ?> 
						<?php if ($carovl['result']['verified'] == 1) { ?> 
						<span class="verified-user">
							<i class="fa fa-check-circle" title="<?php echo $carovl['lang']['verified_user']; ?>" data-toggle="tooltip"></i>
						</span>
						<?php } ?>
						<?php } ?>
					</h6>
					<?php if (! empty($carovl['result']['group_id'])) { ?> 
					<div class="search-groups">
						<?php 
						$members = countGroupMembers($carovl['result']['group_id']);
						if ($members == 0) {
							$people = '';
						} elseif ($members == 1) {
							$people = $carovl['lang']['member'];
						} elseif ($members > 1) {
							$people = $carovl['lang']['members'];
						}
						?>
						<?php echo $carovl['result']['group_title']; ?> (<?php echo $members . ' ' . $people; ?>)
					</div>
					<?php } else { ?> 
					<?php if ($carovl['config']['user_lastseen'] == 1 && $carovl['result']['show_lastseen'] != 0) { ?> 
					<div class="search-user-lastseen">
						<?php echo userStatus($carovl['result']['user_id'], $carovl['result']['lastseen']); ?>
					</div>
					<?php } ?>
					<?php } ?>
				</div>
				<img src="<?php echo $carovl['result']['avatar']; ?>" alt="<?php echo $carovl['result']['username']; ?>">
			</div>
		</a>
	</span>
</li>