<div class="row">
	<div class="col-md-8">
		<div class="card">
			<div class="card-header">
				<h2><?php echo $carovl['lang']['reset_password']; ?></h2>
				<h4 class="dark-color"><?php echo $carovl['lang']['reset_password_desc']; ?></h4>
			</div>
			<div class="card-block">
				<div class="alerts"></div>
				<form method="post" class="forgot-form">
					<div class="form-group carovl">
						<input type="text" name="email" class="form-control">
						<span class="highlight"></span>
						<span class="bar"></span>
						<label><?php echo $carovl['lang']['email_label']; ?></label>
					</div>
					<div class="submit-button">
						<button type="submit" class="btn btn-carovl" id="reset-password">
						<i class="fa fa-envelope icon-loader"></i> <?php echo $carovl['lang']['reset_password_label']; ?></button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(function () {
	$('form.forgot-form').ajaxForm({
		url: ajaxRequests() + '?f=forgot_password',
		beforeSend: function () {
			progressLoader($('#reset-password'));
			$('#reset-password').attr('disabled', true);
		},
		success: function (data) {
			if (data.status == 200) {
				$('.alerts').html('<center><div class="alert alert-success">' + data.success + '</div></center>');
				$('.alert-success').fadeIn('fast', function () {
					$(this).delay(2500).fadeOut(300, function () {
						$(this).remove();
					});
				});
				$('#reset-password').html('<i class="fa fa-check"></i> <?php echo $carovl['lang']['sent_label']; ?>')
			} else {
				$('#reset-password').attr('disabled', false);
				var errors = data.errors.join("<br>");
				$('.alerts').html('<center><div class="alert alert-danger">' + errors + '</div></center>');
				$('.alert-danger').fadeIn('fast', function () {
					$(this).delay(2500).fadeOut(300, function () {
						$(this).remove();
					});
				});
			}
			progressLoader($('#reset-password'));
		}
	});
});
</script>