<div class="row">
	<div class="col-md-8">
		<div class="card">
			<div class="card-header">
				<h2><?php echo $carovl['lang']['create_new_password']; ?></h2>
			</div>
			<div class="card-block">
				<div class="alerts"></div>
				<form method="post" class="forgot-form">
					<div class="form-group carovl">
						<input type="password" name="password" class="form-control">
						<span class="highlight"></span>
						<span class="bar"></span>
						<label><?php echo $carovl['lang']['new_password_label']; ?></label>
					</div>
					<input type="hidden" name="id" value="<?php echo $_GET['code']; ?>">
					<div class="submit-button">
						<button type="submit" class="btn btn-carovl" id="reset-password">
						<i class="fa fa-sign-in icon-loader"></i> <?php echo $carovl['lang']['reset_password_label']; ?></button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(function () {
	$('form.forgot-form').ajaxForm({
		url: ajaxRequests() + '?f=reset_password',
		beforeSend: function () {
			progressLoader($('#reset-password'));
			$('#reset-password').attr('disabled', true);
		},
		success: function (data) {
			if (data.status == 200) {
				$('.card-header').html('<h2>' + data.success + '</h2>');
				setTimeout(function() {
					window.location.href = data.location;
				}, 1000);
			} else {
				$('#reset-password').attr('disabled', false);
				var errors = data.errors.join("<br>");
				$('.alerts').html('<center><div class="alert alert-danger">' + errors + '</div></center>');
				$('.alert-danger').fadeIn('fast', function () {
					$(this).delay(2500).fadeOut(300, function () {
						$(this).remove();
					});
				});
			}
			progressLoader($('#reset-password'));
		}
	});
});
</script>