<div class="card admin">
	<div class="card-header">
		<h3 class="card-title"><?php echo $carovl['lang']['online_users']; ?></h3>
	</div>
	<div class="card-block">
		<div class="table-responsive">
			<table class="table table-hover table-condensed">
				<thead>
					<tr>
						<th><?php echo $carovl['lang']['id']; ?></th>
						<th><?php echo $carovl['lang']['username_label']; ?></th>
						<th><?php echo $carovl['lang']['email_label']; ?></th>
						<th><?php echo $carovl['lang']['ip_address']; ?></th>
						<th><?php echo $carovl['lang']['status']; ?></th>
						<th><?php echo $carovl['lang']['action']; ?></th>
					</tr>
				</thead>
				<tbody class="result user-list">
					<?php 
					foreach (getAllOnlineUsers() as $carovl['user_list']) {
						echo loadPage('admin/users/user-list');
					}
					?>
				</tbody>
			</table>
		</div>
		<input type="hidden" name="hash_id" value="<?php echo createSession(); ?>">
	</div>
</div>