<div class="col-md-10 offset-md-1">
	<div class="row">
		<div class="col-md-8">
			<div class="card activities">
				<div class="card-header">
					<h3 class="card-title"><?php echo $carovl['lang']['activity']; ?><span class="float-right"><i class="fa fa-history fa-fw"></i></span></h3>
				</div>
				<div class="card-block" id="activities">
					<?php
					$activities = getActivities();
					if (count($activities) == 0) { ?>
						<div class="text-center">
							<h5 class="mt-3 mb-3"><?php echo $carovl['lang']['no_data']; ?></h5>
						</div>
					<?php } else {
						foreach ($activities as $carovl['activity']) {
							echo loadPage('activity/activity-list');
						}
					}
					?>
				</div>
			</div>
			<?php if (count($activities) > 0) { ?> 
			<div class="load-more-activities text-center" id="load-more-activities">
				<span class="pointer" onclick="getMoreActivity();"><i class="fa fa-chevron-circle-down icon-loader" data-icon="chevron-circle-down"></i> <?php echo $carovl['lang']['more_activity']; ?></span>
			</div>
			<?php } ?>
			<div class="no-activities"></div>
		</div>
		<div class="col-md-4">
			<?php echo loadPage('sidebar/content'); ?>
		</div>
	</div>
</div>